### ISSUE TITLE
Make it public

### ISSUE THREAD

**Issue by ZLY201** [ji-ba-app/ji-ba-pccweb#1]
You can make this site public and enable the github pages.

We decide to  open source the models and add non commercial protocols.

**Comment by ZLY201** [comment]
@noname0310

**Comment by noname0310** [comment]
Okay. If you change your mind, feel free change it to private

**Comment by ZLY201** [comment]
I think it is okay, this repository will be provided as a free demonstration version, and if you want to have full functionality, you will need to pay to use it on other sites in the future
