### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by ZLY201** [ji-ba-app/ji-ba-pccweb#3]
I think change the top-bottom layout to left-right layout is better.

So that it can run well both at PC and mobile or other. I will turn my phone into landscape mode when load this page.

**Comment by noname0310** [comment]
It now supports both landscape mode and portrait mode

**Comment by ZLY201** [comment]
![image](https://github.com/ji-ba-app/ji-ba-pccweb/assets/59038614/85c7ecd3-c6cc-4b8a-8300-c52201deb429)
it seems not correct?

**Comment by noname0310** [comment]
Did you disable cache?

**Comment by ZLY201** [comment]
> Did you disable cache?

In the PC mode work well.

**Comment by noname0310** [comment]
It's probably fixed now
